@startuml




  class FireBrigadeAdapter implements IVehicle {
     private IFireBrigade iFireBrigade;

     FireBrigadeAdapter(IFireBrigade iFireBrigade)

         this.iFireBrigade = iFireBrigade;

    String drive()


    String quincheFire()

     }
      interface IFireBrigade {
    String turnOnSiren();
    String drive();
}
 class FireBrigade extends Vehicle implements IFireBrigade {


     FireBrigade(){

        this.setType(" Fire Brigade");

    }


 abstract class Vehicle implements IVehicle{

    private String type;

    public void setType(String type){


      String getRescueType()


     String quincheFire()



     String drive()



}






@enduml