@startuml

class Ambulance extends Vehicle {


    public Ambulance(){

        this.setType("Ambulance");

    }
    interface IVehicle {
        String drive();
        String quincheFire();
    }


     abstract class Vehicle implements IVehicle{
        private String type

    }
    interface IFireBrigade {
        String turnOnSiren();
        String drive();
    }
    class FireBrigade extends Vehicle implements IFireBrigade {
        public FireBrigade()

}
            class GardaVehicleFactory extends VehicleFactory{
                @Override
                public Vehicle makeVehicle(String type) {


                }
                class RoadUserVehicleFactory extends VehicleFactory{
                    @Override
                    public IVehicle makeVehicle(String type){

                }
                abstract class VehicleFactory {

                    public abstract IVehicle makeVehicle(String type);

                    public static VehicleFactory getVehicleFactory(String type)


                    }


@enduml