@startuml

 class Walker extends RoadUser {

   public Walker()
       super();
       drivingBehaviour = new CantDrive();
       lightBehaviour = new CannotTurnOnHeadLights();


}
 class TractorDriver extends RoadUser {


    public TractorDriver(){

        super();
    drivingBehaviour = new DrivingUnder30();
    lightBehaviour = new TurnOnHeadLights(); {
}
 class CarDriver extends RoadUser {

    public CarDriver(){
        super();
        drivingBehaviour = new DrivingOver60();
        lightBehaviour = new TurnOnHeadLights();

}
 interface LightBehaviour {
    String turnOnLights();
}
 class DrivingOver60 implements DrivingBehaviour {

    @Override
    public String drive(){
        return "driving over 60";
  class MotorBikeDriver extends RoadUser {

}
 class DrivingUnder30 implements DrivingBehaviour {

    @Override
    public String drive(){
        return "driving under 30 miles an hour";

}
@enduml