@startuml

class BreathiliseTractorDriver extends PullOver{

    public BreathiliseTractorDriver(RoadUser tractorDriver){

        super(tractorDriver);

    public void breathaliser() {

}
 class BreatiliseCarDriver extends PullOver{

    public BreatiliseCarDriver(RoadUser carDriver){

        super(carDriver)


    public void breathaliser()

}
abstract class PullOver {


    public PullOver(RoadUser stoppedDriver)


    public void pulledOver()




    public void namePlease()


    public void speeding(){


    public void stillSpeeding()

    public void breathaliser()

}
@enduml